# Generated by Django 4.0.3 on 2022-04-12 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userFirstName', models.CharField(max_length=50)),
                ('userLastName', models.CharField(max_length=50)),
                ('userDateOfBirth', models.DateField()),
                ('userRegistration', models.DateField()),
                ('isUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isModerator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guideFirstName', models.CharField(max_length=50)),
                ('guideLastName', models.CharField(max_length=50)),
                ('guideDescription', models.TextField(max_length=300)),
                ('isGuide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TourExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tourTitle', models.CharField(max_length=100)),
                ('tourLocation', models.CharField(max_length=50)),
                ('tourDuration', models.IntegerField()),
                ('tourPrice', models.FloatField()),
                ('tourAvailableDate', models.DateField()),
                ('tourMaxNumberOfPeople', models.IntegerField()),
                ('tourDescription', models.TextField(max_length=300)),
                ('tourGuide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tourguide')),
            ],
        ),
    ]
