# Generated by Django 4.0.3 on 2022-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduser',
            old_name='user_registration',
            new_name='userRegistration',
        ),
        migrations.AddField(
            model_name='enduser',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='isGuide',
            field=models.BooleanField(default=False),
        ),
    ]
